In [74]:
import pandas as pd
import numpy as np
import os
from IPython.display import display, HTML
import openpyxl
import sqlite3 as lite
import matplotlib.pyplot as plt
import dataframe_image as dfi

In [4]:
os.chdir(r'/Users/matthewtorretta/Library/CloudStorage/OneDrive-UniversityCollegeDublin/Fin42110Datasci/FDS PROJECT')

In [5]:
read_file = pd.read_excel(r'Share Class Results.xlsx', sheet_name = 'Shareclasses')
read_file.to_csv(r'Share Class Results.csv', index = None, header=True)

In [6]:
df = pd.read_csv('Share Class Results.csv')
df.shape

(8786, 127)

In [7]:
date_cols=df.filter(regex=" date.*",axis=1).columns
df[date_cols]=df[date_cols].apply(pd.to_datetime, errors='coerce')

In [8]:
display(HTML(df[0:10].to_html()))

In [9]:
#Going to be foccussing on the E in ESG 
category = 'Fossil Free Funds'
display(HTML(df.filter(regex=category+".*",axis=1).describe().to_html()))

In [10]:
# Descriptions of all the Categories
key_df=pd.read_excel(r'Share Class Results.xlsx', sheet_name = 'Key',  
                     engine='openpyxl', header=None, names=['Category', 'Feature', 'Description'])
s = key_df.head(10).style.set_properties(**{'text-align': 'left'})
display(HTML(s.render()))

## Cleaning

In [11]:
selected_columns = 

df[[ "Fund profile: Shareclass name", "Fund profile: Ticker", \
     "Fund profile: Shareclass type", 
     "Fund profile: Fund net assets", \
     "Fossil Free Funds: Fossil fuel grade", \
     "Fund profile: Sustainability mandate", \ 
     "Fossil Free Funds: Fossil fuel holdings, weight", \
     "Fossil Free Funds: Relative carbon footprint (tonnes CO2 / $1M USD invested)", \
     "Fossil Free Funds: Clean200, weight"]]

In [67]:
clean_df = selected_columns.copy()
clean_df.dropna()
clean_df["Fund profile: Sustainability mandate"] = clean_df["Fund profile: Sustainability mandate"].fillna('N')

In [84]:
color_mapping = {'A': 'green', 'B': 'lightgreen', 'C': 'yellow', 'D': 'orange', 'F': 'red'}
FFF = clean_df[0:51].style.\
                    applymap(lambda v: f"background-color: {color_mapping.get(v, '')}") \
                    .format({
                    'Fossil Free Funds: Fossil fuel holdings, weight': '{:,.2%}'.format,
                    'Fossil Free Funds: Clean200, weight': '{:,.2%}'.format,
                    'Fund profile: Fund net assets': '${:,.2f}'.format,
                    'Fossil Free Funds: Relative carbon footprint (tonnes CO2 / $1M USD invested)': '{:,.2f}'.format,
                            })
FFF

 ## DATABASE Creation

In [ ]:
con = lite.connect('FossilFreeFunds.db')
clean_df.to_sql(name="FFF", con = con, if_exists = 'replace', index = False)
con.commit()
cur = con.cursor()

In [77]:
Qry = '''SELECT * FROM FFF'''
FFF = pd.read_sql_query(Qry, con)
FFF.head(10)

,Fund profile: Shareclass name,Fund profile: Ticker,Fund profile: Shareclass type,Fund profile: Fund net assets,Fossil Free Funds: Fossil fuel grade,Fund profile: Sustainability mandate,"Fossil Free Funds: Fossil fuel holdings, weight",Fossil Free Funds: Relative carbon footprint (tonnes CO2 / $1M USD invested),"Fossil Free Funds: Clean200, weight"
0,13D Activist A,DDDAX,Open-end mutual fund,262465052,C,Y,0.052510,175.67,0.024756
1,13D Activist C,DDDCX,Open-end mutual fund,262465052,C,Y,0.052510,175.67,0.024756
2,13D Activist I,DDDIX,Open-end mutual fund,262465052,C,Y,0.052510,175.67,0.024756
3,1919 Socially Responsive Balanced A,SSIAX,Open-end mutual fund,876040745,A,Y,0.000000,27.47,0.168076
4,1919 Socially Responsive Balanced C,SESLX,Open-end mutual fund,876040745,A,Y,0.000000,27.47,0.168076
5,1919 Socially Responsive Balanced I,LMRNX,Open-end mutual fund,876040745,A,Y,0.000000,27.47,0.168076
6,AGF Global Sustainable Equity I,AGPIX,Open-end mutual fund,1892171,A,Y,0.000000,35.59,0.357263
7,AGF Global Sustainable Equity R6,AGPRX,Open-end mutual fund,1892171,A,Y,0.000000,35.59,0.357263
8,ALPS Clean Energy ETF,ACES,ETF,752189837,B,Y,0.004277,210.29,0.537231
9,ALPS/Kotak India Growth A,INAAX,Open-end mutual fund,398952085,F,Y,0.091551,128.46,0.026579

## Top ten Sustainable funds

In [78]:
 Qry = '''SELECT * FROM FFF 
        WHERE "Fossil Free Funds: Fossil fuel grade" =="A" AND
        "Fund profile: Sustainability mandate" == "Y"
        ORDER BY 
        "Fossil Free Funds: Fossil fuel holdings, weight" ASC,
        "Fund profile: Fund net assets" DESC,
        "Fossil Free Funds: Relative carbon footprint (tonnes CO2 / $1M USD invested)" ASC,
        "Fossil Free Funds: Clean200, weight" DESC; '''

Top10 = pd.read_sql_query(Qry, con)
Top10.head(10)

#cur.execute(Qry)
#result = cur.fetchall()
#result

,Fund profile: Shareclass name,Fund profile: Ticker,Fund profile: Shareclass type,Fund profile: Fund net assets,Fossil Free Funds: Fossil fuel grade,Fund profile: Sustainability mandate,"Fossil Free Funds: Fossil fuel holdings, weight",Fossil Free Funds: Relative carbon footprint (tonnes CO2 / $1M USD invested),"Fossil Free Funds: Clean200, weight"
0,Parnassus Core Equity Institutional,PRILX,Open-end mutual fund,30580840779,A,Y,0.0,36.81,0.217650
1,Parnassus Core Equity Investor,PRBLX,Open-end mutual fund,30580840779,A,Y,0.0,36.81,0.217650
2,Brown Advisory Sustainable Growth Adv,BAWAX,Open-end mutual fund,6547957022,A,Y,0.0,5.40,0.266624
3,Brown Advisory Sustainable Growth I,BAFWX,Open-end mutual fund,6547957022,A,Y,0.0,5.40,0.266624
4,Brown Advisory Sustainable Growth Inv,BIAWX,Open-end mutual fund,6547957022,A,Y,0.0,5.40,0.266624
5,Eventide Gilead A,ETAGX,Open-end mutual fund,5433278949,A,Y,0.0,40.23,0.058553
6,Eventide Gilead C,ETCGX,Open-end mutual fund,5433278949,A,Y,0.0,40.23,0.058553
7,Eventide Gilead I,ETILX,Open-end mutual fund,5433278949,A,Y,0.0,40.23,0.058553
8,Eventide Gilead N,ETGLX,Open-end mutual fund,5433278949,A,Y,0.0,40.23,0.058553
9,Parnassus Endeavor Institutional,PFPWX,Open-end mutual fund,5408906173,A,Y,0.0,24.00,0.177070

## Bottom Ten funds

In [62]:
Qry = '''SELECT * FROM FFF 
        WHERE "Fund profile: Ticker" not like 'None' AND
        "Fossil Free Funds: Fossil fuel grade" =="F" AND
        "Fund profile: Sustainability mandate" == "N"
        ORDER BY 
        "Fossil Free Funds: Fossil fuel holdings, weight" DESC,
        "Fund profile: Fund net assets" DESC,
        "Fossil Free Funds: Relative carbon footprint (tonnes CO2 / $1M USD invested)" DESC,
        "Fossil Free Funds: Clean200, weight" DESC; '''

Bottom10 = pd.read_sql_query(Qry, con)
Bottom10.head(10)

,Fund profile: Shareclass name,Fund profile: Ticker,Fund profile: Shareclass type,Fund profile: Fund net assets,Fossil Free Funds: Fossil fuel grade,Fund profile: Sustainability mandate,"Fossil Free Funds: Fossil fuel holdings, weight",Fossil Free Funds: Relative carbon footprint (tonnes CO2 / $1M USD invested),"Fossil Free Funds: Clean200, weight"
0,Invesco Dynamic Engy Explr & Prdtn ETF,PXE,ETF,206018882,F,N,1.000000,471.47,0.000000
1,VanEck Oil Services ETF,OIH,ETF,2926934318,F,N,0.999863,138.59,0.000000
2,First Trust Nasdaq Oil & Gas ETF,FTXN,ETF,1220794291,F,N,0.999777,402.75,0.000000
3,First Trust Natural Gas ETF,FCG,ETF,586372773,F,N,0.998916,386.89,0.000000
4,Invesco Dynamic Oil & Gas Services ETF,PXJ,ETF,31610807,F,N,0.996427,101.91,0.000000
5,iShares US Oil & Gas Explor & Prod ETF,IEO,ETF,656812315,F,N,0.996297,447.21,0.000000
6,JHancock Multifactor Energy ETF,JHME,ETF,28481895,F,N,0.995893,367.50,0.000000
7,Fidelity® Select Energy,FSENX,Open-end mutual fund,1574923178,F,N,0.992913,659.86,0.000962
8,Energy Select Sector SPDR® ETF,XLE,ETF,36028031498,F,N,0.992181,362.17,0.000000
9,Vanguard Energy ETF,VDE,ETF,8445108822,F,N,0.991349,373.30,0.002427

## Base Middle Fund

In [63]:
Qry = '''SELECT AVG("Fossil Free Funds: Fossil fuel holdings, weight")
            FROM (SELECT "Fossil Free Funds: Fossil fuel holdings, weight"
                  FROM FFF
                  ORDER BY "Fossil Free Funds: Fossil fuel holdings, weight"
                  LIMIT 2 - (SELECT COUNT(*) FROM FFF) % 2    -- odd 1, even 2
                  OFFSET (SELECT (COUNT(*) - 1) / 2
                          FROM FFF))'''

cur.execute(Qry)
result = cur.fetchall()
result

[(0.0543760054639663,)]

In [64]:
Qry = '''SELECT * FROM FFF ORDER BY ABS(0.054376 - "Fossil Free Funds: Fossil fuel holdings, weight") LIMIT 1 '''
Median = pd.read_sql_query(Qry, con)
Median

,Fund profile: Shareclass name,Fund profile: Ticker,Fund profile: Shareclass type,Fund profile: Fund net assets,Fossil Free Funds: Fossil fuel grade,Fund profile: Sustainability mandate,"Fossil Free Funds: Fossil fuel holdings, weight",Fossil Free Funds: Relative carbon footprint (tonnes CO2 / $1M USD invested),"Fossil Free Funds: Clean200, weight"
0,JPMorgan SmartRetirement® 2045 A,JSAAX,Open-end mutual fund,3951741543,C,N,0.054376,0.0,0.116221

In [79]:
con.commit()
con.close()